##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Fri Apr 29 19:58:34 2022

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path test_proteins/ASH66.pqr
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=0)
NOsh: Parsing ELEC section
NOsh_parseBEM: Parsing parameters for BEM calculation
NOsh_parseBEM:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseBEM:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseBEM:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseBEM:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseBEM:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseBEM:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseBEM:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseBEM:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseBEM:  Parsing tree_order...
PBEparm_parseToken:  trying tree_order...
BEMparm_parseToken:  trying tree_order...
NOsh_parseBEM:  Parsing tree_n0...
PBEparm_parseToken:  trying tree_n0...
BEMparm_parseToken:  trying tree_n0...
NOsh_parseBEM:  Parsing mac...
PBEparm_parseToken:  trying mac...
BEMparm_parseToken:  trying mac...
NOsh_parseBEM:  Parsing mesh...
PBEparm_parseToken:  trying mesh...
BEMparm_parseToken:  trying mesh...
NOsh_parseBEM:  Parsing outdata...
PBEparm_parseToken:  trying outdata...
BEMparm_parseToken:  trying outdata...
NOsh_parseBEM:  Parsing end...
BEMparm_check:  checking BEMparm object of type 0.
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readPQR: Counted 13 atoms
Valist_getStatistics:  Max atom coordinate:  (3.057, 1.146, 34.123)
Valist_getStatistics:  Min atom coordinate:  (-1.147, -2.784, 31.226)
Valist_getStatistics:  Molecule center:  (0.955, -0.819, 32.6745)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vnm_tstart: starting timer 27 (Setup timer)..
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.201000e+01
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 0.000000e+00
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 1.201700e+01
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Fri Apr 29 19:58:46 2022

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path test_proteins/2LZT-ASH66.pqr
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=0)
NOsh: Parsing ELEC section
NOsh_parseBEM: Parsing parameters for BEM calculation
NOsh_parseBEM:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseBEM:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseBEM:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseBEM:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseBEM:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseBEM:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseBEM:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseBEM:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseBEM:  Parsing tree_order...
PBEparm_parseToken:  trying tree_order...
BEMparm_parseToken:  trying tree_order...
NOsh_parseBEM:  Parsing tree_n0...
PBEparm_parseToken:  trying tree_n0...
BEMparm_parseToken:  trying tree_n0...
NOsh_parseBEM:  Parsing mac...
PBEparm_parseToken:  trying mac...
BEMparm_parseToken:  trying mac...
NOsh_parseBEM:  Parsing mesh...
PBEparm_parseToken:  trying mesh...
BEMparm_parseToken:  trying mesh...
NOsh_parseBEM:  Parsing outdata...
PBEparm_parseToken:  trying outdata...
BEMparm_parseToken:  trying outdata...
NOsh_parseBEM:  Parsing end...
BEMparm_check:  checking BEMparm object of type 0.
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readPQR: Counted 1961 atoms
Valist_getStatistics:  Max atom coordinate:  (16.282, 33.31, 44.415)
Valist_getStatistics:  Min atom coordinate:  (-14.194, -5.145, -1.92)
Valist_getStatistics:  Molecule center:  (1.044, 14.0825, 21.2475)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vnm_tstart: starting timer 27 (Setup timer)..
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 6.188800e+01
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 0.000000e+00
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 6.191100e+01
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Fri Apr 29 19:59:48 2022

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path test_proteins/2LZT-noASH66.pqr
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=0)
NOsh: Parsing ELEC section
NOsh_parseBEM: Parsing parameters for BEM calculation
NOsh_parseBEM:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseBEM:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseBEM:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseBEM:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseBEM:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseBEM:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseBEM:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseBEM:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseBEM:  Parsing tree_order...
PBEparm_parseToken:  trying tree_order...
BEMparm_parseToken:  trying tree_order...
NOsh_parseBEM:  Parsing tree_n0...
PBEparm_parseToken:  trying tree_n0...
BEMparm_parseToken:  trying tree_n0...
NOsh_parseBEM:  Parsing mac...
PBEparm_parseToken:  trying mac...
BEMparm_parseToken:  trying mac...
NOsh_parseBEM:  Parsing mesh...
PBEparm_parseToken:  trying mesh...
BEMparm_parseToken:  trying mesh...
NOsh_parseBEM:  Parsing outdata...
PBEparm_parseToken:  trying outdata...
BEMparm_parseToken:  trying outdata...
NOsh_parseBEM:  Parsing end...
BEMparm_check:  checking BEMparm object of type 0.
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readPQR: Counted 1961 atoms
Valist_getStatistics:  Max atom coordinate:  (16.282, 33.31, 44.415)
Valist_getStatistics:  Min atom coordinate:  (-14.194, -5.145, -1.92)
Valist_getStatistics:  Molecule center:  (1.044, 14.0825, 21.2475)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vnm_tstart: starting timer 27 (Setup timer)..
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 6.311400e+01
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 0.000000e+00
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 6.313900e+01
