#!/usr/bin/env python3
"""Generate `src/enum_names.rs` from the GROMACS 2026.3 sources.

`gmx dump` prints nearly every inputrec field through `enumValueToString()`,
so the Rust port needs the exact same spelling of every enum value.  The
tables below live in the C++ sources as

    static constexpr gmx::EnumerationArray<SomeEnum, const char*> names = {
        "first", "second", ...
    };

and are extracted here verbatim so that no name can be mistyped by hand.

Usage:  scripts/gen_enum_names.py [gromacs-source-root] > src/enum_names.rs
"""

import os
import re
import sys

SRC_ROOT = sys.argv[1] if len(sys.argv) > 1 else "."

TABLE_RE = re.compile(
    r"EnumerationArray<\s*(?:gmx::)?([A-Za-z_][A-Za-z0-9_:]*)\s*,\s*(?:const\s+char\s*\*|std::string)\s*>"
    r"\s*([A-Za-z_][A-Za-z0-9_]*)\s*(?:=|\{)?",
)


def camel_to_snake(name):
    name = name.split("::")[-1]
    out = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0 and not name[i - 1].isupper():
            out.append("_")
        out.append(ch.lower())
    return "".join(out)


def read_table(text, start):
    """Reads the brace list starting at `start` (index of '{')."""
    assert text[start] == "{"
    depth = 0
    i = start
    while i < len(text):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                break
        i += 1
    return text[start : i + 1], i + 1


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"//[^\n]*", "", text)
    return text


def parse_entries(body):
    entries = []
    for match in re.finditer(r'"((?:[^"\\]|\\.)*)"', body):
        entries.append(match.group(1))
    if not entries:
        raise ValueError(f"no string literals in {body!r}")
    return entries


def main():
    # `enumValueToString()` is authoritative: it is what `gmx dump` prints.
    authoritative = {}
    candidates = {}
    sources = []
    for root, _, files in os.walk(os.path.join(SRC_ROOT, "src", "gromacs")):
        for name in sorted(files):
            if name.endswith((".cpp", ".h")):
                sources.append(os.path.join(root, name))
    for path in sorted(sources):
        if "/tests/" in path:
            continue
        with open(path, encoding="utf-8", errors="replace") as handle:
            text = strip_comments(handle.read())

        # `const char* enumValueToString(SomeEnum enumValue) { ... }`
        for match in re.finditer(
            r"const char\*\s+enumValueToString\(\s*(?:gmx::)?([A-Za-z_][A-Za-z0-9_:]*)\s+enumValue\s*\)",
            text,
        ):
            enum_name = match.group(1)
            brace = text.find("{", match.end())
            if brace < 0:
                continue
            body, _ = read_table(text, brace)
            eq = body.find("=")
            if eq < 0:
                continue
            inner = body.find("{", eq)
            if inner < 0:
                continue
            try:
                entries_body, _ = read_table(body, inner)
                entries = parse_entries(entries_body)
            except (ValueError, AssertionError):
                continue
            authoritative[camel_to_snake(enum_name)] = (enum_name, entries, path)

        for match in TABLE_RE.finditer(text):
            enum_name = match.group(1)
            brace = text.find("{", match.end() - 1)
            if brace < 0 or brace > match.end() + 2:
                continue
            try:
                body, _ = read_table(text, brace)
                entries = parse_entries(body)
            except (ValueError, AssertionError):
                continue
            key = camel_to_snake(enum_name)
            candidates.setdefault(key, []).append((enum_name, entries, path))

    tables = {}
    for key, value in candidates.items():
        if key in authoritative:
            continue
        distinct = {tuple(entries) for _, entries, _ in value}
        if len(distinct) > 1:
            paths = ", ".join(os.path.relpath(p, SRC_ROOT) for _, _, p in value)
            print(f"// WARNING: conflicting tables for {key}: {paths}", file=sys.stderr)
        tables[key] = sorted(value, key=lambda item: item[2])[0]
    for key, value in authoritative.items():
        tables[key] = value

    print("//! Enum value names extracted from the GROMACS 2026.3 sources.")
    print("//!")
    print("//! Generated by `scripts/gen_enum_names.py`; do not edit by hand.")
    print("//! These are the exact strings `enumValueToString()` returns, which is")
    print("//! what `gmx dump` prints for every enum valued inputrec field.")
    print()
    print("#![allow(dead_code)]")
    print()
    print("/// Mirrors `enumValueToString(int)`, which returns this string for an")
    print("/// out of range enum value (the typed overloads index out of bounds).")
    print('pub const NO_NAME_DEFINED: &str = "no name defined";')
    print()
    print("/// Looks up `value` in `table`, clamping to `NO_NAME_DEFINED`.")
    print("pub fn lookup(table: &[&'static str], value: i64) -> &'static str {")
    print("    if value < 0 || value as usize >= table.len() {")
    print("        return NO_NAME_DEFINED;")
    print("    }")
    print("    table[value as usize]")
    print("}")
    print()
    for key in sorted(tables):
        enum_name, entries, path = tables[key]
        rel = os.path.relpath(path, SRC_ROOT)
        print(f"/// `{enum_name}` (from `{rel}`).")
        print(f"pub static {key.upper()}: &[&str] = &[")
        for entry in entries:
            escaped = entry.replace("\\", "\\\\").replace('"', '\\"')
            print(f'    "{escaped}",')
        print("];")
        print()


if __name__ == "__main__":
    main()
