//! Enum value names extracted from the GROMACS 2026.3 sources.
//!
//! Generated by `scripts/gen_enum_names.py`; do not edit by hand.
//! These are the exact strings `enumValueToString()` returns, which is
//! what `gmx dump` prints for every enum valued inputrec field.

#![allow(dead_code)]

/// Mirrors `enumValueToString(int)`, which returns this string for an
/// out of range enum value (the typed overloads index out of bounds).
pub const NO_NAME_DEFINED: &str = "no name defined";

/// Looks up `value` in `table`, clamping to `NO_NAME_DEFINED`.
pub fn lookup(table: &[&'static str], value: i64) -> &'static str {
    if value < 0 || value as usize >= table.len() {
        return NO_NAME_DEFINED;
    }
    table[value as usize]
}

/// `ActiveFmmBackend` (from `src/gromacs/fmm/fmmoptions.h`).
pub static ACTIVE_FMM_BACKEND: &[&str] = &[
    "inactive",
    "exafmm",
    "fmsolvr",
];

/// `ArginineStates` (from `src/gromacs/gmxpreprocess/pdb2gmx.cpp`).
pub static ARGININE_STATES: &[&str] = &[
    "ARGN",
    "ARG",
];

/// `AspartateStates` (from `src/gromacs/gmxpreprocess/pdb2gmx.cpp`).
pub static ASPARTATE_STATES: &[&str] = &[
    "ASP",
    "ASPH",
];

/// `AtomLocality` (from `src/gromacs/mdtypes/locality.h`).
pub static ATOM_LOCALITY: &[&str] = &[
    "Local",
    "Non-local",
    "All",
];

/// `AwhCoordinateProviderType` (from `src/gromacs/applied_forces/awh/read_params.cpp`).
pub static AWH_COORDINATE_PROVIDER_TYPE: &[&str] = &[
    "pull",
    "fep-lambda",
];

/// `AwhHistogramGrowthType` (from `src/gromacs/applied_forces/awh/read_params.cpp`).
pub static AWH_HISTOGRAM_GROWTH_TYPE: &[&str] = &[
    "exp-linear",
    "linear",
];

/// `AwhPotentialType` (from `src/gromacs/applied_forces/awh/read_params.cpp`).
pub static AWH_POTENTIAL_TYPE: &[&str] = &[
    "convolved",
    "umbrella",
];

/// `AwhTargetType` (from `src/gromacs/applied_forces/awh/read_params.cpp`).
pub static AWH_TARGET_TYPE: &[&str] = &[
    "constant",
    "cutoff",
    "boltzmann",
    "local-boltzmann",
];

/// `BackboneAtomTypes` (from `src/gromacs/trajectoryanalysis/modules/dssp.cpp`).
pub static BACKBONE_ATOM_TYPES: &[&str] = &[
    "CA",
    "C",
    "O",
    "N",
    "H",
    "HN",
];

/// `BondedKernelFlavor` (from `src/gromacs/listed_forces/bonded.cpp`).
pub static BONDED_KERNEL_FLAVOR: &[&str] = &[
    "forces, using SIMD when available",
    "forces, not using SIMD",
    "forces, virial, and energy (ie. not using SIMD)",
    "forces and energy (ie. not using SIMD)",
];

/// `BondedTypes` (from `src/gromacs/gmxpreprocess/hackblock.cpp`).
pub static BONDED_TYPES: &[&str] = &[
    "bonds",
    "angles",
    "dihedrals",
    "impropers",
    "exclusions",
    "cmap",
];

/// `Boolean` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static BOOLEAN: &[&str] = &[
    "no",
    "yes",
];

/// `CenteringType` (from `src/gromacs/pbcutil/pbcenums.cpp`).
pub static CENTERING_TYPE: &[&str] = &[
    "Triclinic",
    "Rectangular",
    "Zero-Based",
];

/// `ChainSeparationType` (from `src/gromacs/gmxpreprocess/pdb2gmx.cpp`).
pub static CHAIN_SEPARATION_TYPE: &[&str] = &[
    "id_or_ter",
    "id_and_ter",
    "ter",
    "id",
    "interactive",
];

/// `ChangeAtomsType` (from `src/gromacs/coordinateio/requirements.cpp`).
pub static CHANGE_ATOMS_TYPE: &[&str] = &[
    "preserved-if-present",
    "always-from-structure",
    "never",
    "always",
];

/// `ChangeSettingType` (from `src/gromacs/coordinateio/requirements.cpp`).
pub static CHANGE_SETTING_TYPE: &[&str] = &[
    "preserved-if-present",
    "always",
    "never",
];

/// `ChannelHistory` (from `src/gromacs/swap/swapcoords.cpp`).
pub static CHANNEL_HISTORY: &[&str] = &[
    "none",
    "channel0",
    "channel1",
];

/// `ComRemovalAlgorithm` (from `src/gromacs/mdlib/vcm.cpp`).
pub static COM_REMOVAL_ALGORITHM: &[&str] = &[
    "Linear",
    "Angular",
    "None",
    "Linear-acceleration-correction",
];

/// `CombinationRule` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static COMBINATION_RULE: &[&str] = &[
    "None",
    "Geometric",
    "Arithmetic",
    "GeomSigEps",
];

/// `Compartment` (from `src/gromacs/swap/swapcoords.cpp`).
pub static COMPARTMENT: &[&str] = &[
    "A",
    "B",
];

/// `ConstraintAlgorithm` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static CONSTRAINT_ALGORITHM: &[&str] = &[
    "Lincs",
    "Shake",
];

/// `CoulombInteractionType` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static COULOMB_INTERACTION_TYPE: &[&str] = &[
    "Cut-off",
    "Reaction-Field",
    "Generalized-Reaction-Field (unused)",
    "PME",
    "Ewald",
    "P3M-AD",
    "Poisson",
    "Switch",
    "Shift",
    "User",
    "Generalized-Born (unused)",
    "Reaction-Field-nec (unsupported)",
    "Encad-shift (unused)",
    "PME-User",
    "PME-Switch",
    "PME-User-Switch",
    "Reaction-Field-zero",
    "FMM",
];

/// `CutoffScheme` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static CUTOFF_SCHEME: &[&str] = &[
    "Verlet",
    "Group",
];

/// `Impl::DebugLevel` (from `src/gromacs/selection/selectioncollection.cpp`).
pub static DEBUG_LEVEL: &[&str] = &[
    "no",
    "basic",
    "compile",
    "eval",
    "full",
];

/// `DensityFittingAmplitudeMethod` (from `src/gromacs/applied_forces/densityfitting/densityfittingoptions.cpp`).
pub static DENSITY_FITTING_AMPLITUDE_METHOD: &[&str] = &[
    "unity",
    "mass",
    "charge",
];

/// `DensitySimilarityMeasureMethod` (from `src/gromacs/applied_forces/densityfitting/densityfittingoptions.cpp`).
pub static DENSITY_SIMILARITY_MEASURE_METHOD: &[&str] = &[
    "inner-product",
    "relative-entropy",
    "cross-correlation",
];

/// `DeprecatedDirectives` (from `src/gromacs/gmxpreprocess/topdirs.cpp`).
pub static DEPRECATED_DIRECTIVES: &[&str] = &[
    "dummies1",
    "dummies2",
    "dummies3",
    "dummies4",
    "dummiesn",
];

/// `DeviceStatus` (from `src/gromacs/hardware/device_information.h`).
pub static DEVICE_STATUS: &[&str] = &[
    "compatible",
    "nonexistent",
    "incompatible",
    "incompatible (please recompile with correct GMX_GPU_NB_CLUSTER_SIZE)",
    "incompatible (please use CUDA build for NVIDIA Volta GPUs or newer)",
    "not recommended (please use ONEAPI_DEVICE_SELECTOR to limit visibility to a single backend)",
    "non-functional",
    "unavailable",
    "not in set of targeted devices",
    "incompatible (AMD RDNA devices are not supported)",
    "incompatible (please recompile with GMX_ENABLE_AMD_RDNA_SUPPORT)",
];

/// `DhDlDerivativeCalculation` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static DH_DL_DERIVATIVE_CALCULATION: &[&str] = &[
    "yes",
    "no",
];

/// `Directive` (from `src/gromacs/gmxpreprocess/topdirs.cpp`).
pub static DIRECTIVE: &[&str] = &[
    "defaults",
    "atomtypes",
    "bondtypes",
    "constrainttypes",
    "pairtypes",
    "angletypes",
    "dihedraltypes",
    "nonbond_params",
    "implicit_genborn_params",
    "implicit_surface_params",
    "cmaptypes",
    "moleculetype",
    "atoms",
    "virtual_sites1",
    "virtual_sites2",
    "virtual_sites3",
    "virtual_sites4",
    "virtual_sitesn",
    "bonds",
    "exclusions",
    "pairs",
    "pairs_nb",
    "angles",
    "dihedrals",
    "constraints",
    "settles",
    "polarization",
    "water_polarization",
    "thole_polarization",
    "system",
    "molecules",
    "position_restraints",
    "angle_restraints",
    "angle_restraints_z",
    "distance_restraints",
    "orientation_restraints",
    "dihedral_restraints",
    "cmap",
    "intermolecular_interactions",
    "maxdirs",
    "invalid",
    "none",
];

/// `DispersionCorrectionType` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static DISPERSION_CORRECTION_TYPE: &[&str] = &[
    "No",
    "EnerPres",
    "Ener",
    "AllEnerPres",
    "AllEner",
];

/// `DistanceRestraintRefinement` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static DISTANCE_RESTRAINT_REFINEMENT: &[&str] = &[
    "No",
    "Simple",
    "Ensemble",
];

/// `DistanceRestraintWeighting` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static DISTANCE_RESTRAINT_WEIGHTING: &[&str] = &[
    "Conservative",
    "Equal",
];

/// `DistanceType` (from `src/gromacs/trajectoryanalysis/modules/pairdist.cpp`).
pub static DISTANCE_TYPE: &[&str] = &[
    "min",
    "max",
];

/// `DlbState` (from `src/gromacs/domdec/domdec.cpp`).
pub static DLB_STATE: &[&str] = &[
    "off",
    "off",
    "auto",
    "locked",
    "on",
    "on",
];

/// `Domain` (from `src/gromacs/swap/swapcoords.cpp`).
pub static DOMAIN: &[&str] = &[
    "not_assigned",
    "Domain_A",
    "Domain_B",
];

/// `EnforcedRotationGroupType` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static ENFORCED_ROTATION_GROUP_TYPE: &[&str] = &[
    "iso",
    "iso-pf",
    "pm",
    "pm-pf",
    "rm",
    "rm-pf",
    "rm2",
    "rm2-pf",
    "flex",
    "flex-t",
    "flex2",
    "flex2-t",
];

/// `EnsembleTemperatureSetting` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static ENSEMBLE_TEMPERATURE_SETTING: &[&str] = &[
    "not available",
    "constant",
    "variable",
    "auto",
];

/// `EwaldGeometry` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static EWALD_GEOMETRY: &[&str] = &[
    "3d",
    "3dc",
];

/// `ExaFmmTreeType` (from `src/gromacs/fmm/fmmoptions.h`).
pub static EXA_FMM_TREE_TYPE: &[&str] = &[
    "uniform",
    "adaptive",
];

/// `FmmDirectProvider` (from `src/gromacs/fmm/fmmoptions.cpp`).
pub static FMM_DIRECT_PROVIDER: &[&str] = &[
    "GROMACS",
    "FMM",
];

/// `Fonts` (from `src/gromacs/fileio/writeps.cpp`).
pub static FONTS: &[&str] = &[
    "Times-Roman",
    "Times-Italic",
    "Times-Bold",
    "Times-BoldItalic",
    "Helvetica",
    "Helvetica-Oblique",
    "Helvetica-Bold",
    "Helvetica-BoldOblique",
    "Courier",
    "Courier-Oblique",
    "Courier-Bold",
    "Courier-BoldOblique",
];

/// `FreeEnergyPerturbationCouplingType` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static FREE_ENERGY_PERTURBATION_COUPLING_TYPE: &[&str] = &[
    "fep-lambdas",
    "mass-lambdas",
    "coul-lambdas",
    "vdw-lambdas",
    "bonded-lambdas",
    "restraint-lambdas",
    "temperature-lambdas",
];

/// `FreeEnergyPerturbationType` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static FREE_ENERGY_PERTURBATION_TYPE: &[&str] = &[
    "no",
    "yes",
    "static",
    "slow-growth",
    "expanded",
];

/// `FreeEnergyPrintEnergy` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static FREE_ENERGY_PRINT_ENERGY: &[&str] = &[
    "no",
    "total",
    "potential",
    "yes",
];

/// `GlutamateStates` (from `src/gromacs/gmxpreprocess/pdb2gmx.cpp`).
pub static GLUTAMATE_STATES: &[&str] = &[
    "GLU",
    "GLUH",
];

/// `GlutamineStates` (from `src/gromacs/gmxpreprocess/pdb2gmx.cpp`).
pub static GLUTAMINE_STATES: &[&str] = &[
    "GLN",
    "QLN",
];

/// `GpuApiCallBehavior` (from `src/gromacs/gpu_utils/gpu_utils.cpp`).
pub static GPU_API_CALL_BEHAVIOR: &[&str] = &[
    "Synchronous",
    "Asynchronous",
];

/// `GpuAwareMpiStatus` (from `src/gromacs/utility/mpiinfo.cpp`).
pub static GPU_AWARE_MPI_STATUS: &[&str] = &[
    "not supported",
    "forced",
    "supported",
];

/// `Group1Type` (from `src/gromacs/trajectoryanalysis/modules/angle.cpp`).
pub static GROUP1_TYPE: &[&str] = &[
    "angle",
    "dihedral",
    "vector",
    "plane",
];

/// `Group2Type` (from `src/gromacs/trajectoryanalysis/modules/angle.cpp`).
pub static GROUP2_TYPE: &[&str] = &[
    "none",
    "vector",
    "plane",
    "t0",
    "z",
    "sphnorm",
];

/// `GroupType` (from `src/gromacs/trajectoryanalysis/modules/pairdist.cpp`).
pub static GROUP_TYPE: &[&str] = &[
    "all",
    "res",
    "mol",
    "none",
];

/// `GyrateMode` (from `src/gromacs/trajectoryanalysis/modules/gyrate.cpp`).
pub static GYRATE_MODE: &[&str] = &[
    "mass",
    "charge",
    "geometry",
];

/// `HBondDefinition` (from `src/gromacs/trajectoryanalysis/modules/dssp.cpp`).
pub static HBOND_DEFINITION: &[&str] = &[
    "energy",
    "geometry",
];

/// `HistidineStates` (from `src/gromacs/gmxpreprocess/pdb2top.cpp`).
pub static HISTIDINE_STATES: &[&str] = &[
    "HISD",
    "HISE",
    "HISH",
    "HIS1",
];

/// `HydrogenMode` (from `src/gromacs/trajectoryanalysis/modules/dssp.cpp`).
pub static HYDROGEN_MODE: &[&str] = &[
    "gromacs",
    "dssp",
];

/// `IMDMessageType` (from `src/gromacs/imd/imd.cpp`).
pub static IMDMESSAGE_TYPE: &[&str] = &[
    "IMD_DISCONNECT",
    "IMD_ENERGIES",
    "IMD_FCOORDS",
    "IMD_GO",
    "IMD_HANDSHAKE",
    "IMD_KILL",
    "IMD_MDCOMM",
    "IMD_PAUSE",
    "IMD_TRATE",
    "IMD_IOERROR",
];

/// `IncompatibilityReasons` (from `src/gromacs/mdlib/updategroups.cpp`).
pub static INCOMPATIBILITY_REASONS: &[&str] = &[
    "flexible constraints are present",
    "an incompatible virtual site type is used",
    "the construction atoms of a virtual site are only partly with a group of constrained atoms",
    "atoms that are (in)directly constrained together are interdispersed with other atoms",
    "there are three or more consecutively coupled constraints",
];

/// `InputOutputType` (from `src/gromacs/fileio/gmxfio_xdr.cpp`).
pub static INPUT_OUTPUT_TYPE: &[&str] = &[
    "REAL",
    "FLOAT",
    "DOUBLE",
    "INT",
    "INT32",
    "INT64",
    "UCHAR",
    "CHAR",
    "NCHAR",
    "NUCHAR",
    "USHORT",
    "RVEC",
    "NRVEC",
    "IVEC",
    "STRING",
    "OPAQUE",
];

/// `IntegrationAlgorithm` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static INTEGRATION_ALGORITHM: &[&str] = &[
    "md",
    "steep",
    "cg",
    "bd",
    "sd2 - removed",
    "nm",
    "l-bfgs",
    "tpi",
    "tpic",
    "sd",
    "md-vv",
    "md-vv-avek",
    "mimic",
];

/// `IntegrationStage` (from `src/gromacs/modularsimulator/propagator.cpp`).
pub static INTEGRATION_STAGE: &[&str] = &[
    "IntegrationStage::PositionsOnly",
    "IntegrationStage::VelocitiesOnly",
    "IntegrationStage::LeapFrog",
    "IntegrationStage::VelocityVerletPositionsAndVelocities",
    "IntegrationStage::ScaleVelocities",
    "IntegrationStage::ScalePositions",
];

/// `InteractionLocality` (from `src/gromacs/mdtypes/locality.h`).
pub static INTERACTION_LOCALITY: &[&str] = &[
    "Local",
    "Non-local",
];

/// `InteractionModifiers` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static INTERACTION_MODIFIERS: &[&str] = &[
    "Potential-shift-Verlet",
    "Potential-shift",
    "None",
    "Potential-switch",
    "Exact-cutoff",
    "Force-switch",
];

/// `KernelSoftcoreType` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static KERNEL_SOFTCORE_TYPE: &[&str] = &[
    "beutler",
    "gapsys",
    "none",
];

/// `LambdaMoveCalculation` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static LAMBDA_MOVE_CALCULATION: &[&str] = &[
    "no",
    "metropolis",
    "barker",
    "gibbs",
    "metropolized-gibbs",
];

/// `LambdaWeightCalculation` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static LAMBDA_WEIGHT_CALCULATION: &[&str] = &[
    "no",
    "metropolis-transition",
    "barker-transition",
    "minvar",
    "wang-landau",
    "weighted-wang-landau",
];

/// `LambdaWeightWillReachEquilibrium` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static LAMBDA_WEIGHT_WILL_REACH_EQUILIBRIUM: &[&str] = &[
    "no",
    "yes",
    "wl-delta",
    "number-all-lambda",
    "number-steps",
    "number-samples",
    "count-ratio",
];

/// `LJCombinationRule` (from `src/gromacs/nbnxm/atomdata.cpp`).
pub static LJCOMBINATION_RULE: &[&str] = &[
    "Geometric",
    "Lorentz-Berthelot",
    "None",
];

/// `LongRangeVdW` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static LONG_RANGE_VD_W: &[&str] = &[
    "Geometric",
    "Lorentz-Berthelot",
];

/// `LysineStates` (from `src/gromacs/gmxpreprocess/pdb2gmx.cpp`).
pub static LYSINE_STATES: &[&str] = &[
    "LYSN",
    "LYS",
];

/// `MergeType` (from `src/gromacs/gmxpreprocess/pdb2gmx.cpp`).
pub static MERGE_TYPE: &[&str] = &[
    "no",
    "all",
    "interactive",
];

/// `ModuleMultiThread` (from `src/gromacs/mdlib/gmx_omp_nthreads.cpp`).
pub static MODULE_MULTI_THREAD: &[&str] = &[
    "default",
    "domain decomposition",
    "pair search",
    "non-bonded",
    "bonded",
    "PME",
    "update",
    "virtual sites",
    "LINCS",
    "SETTLE",
];

/// `MtsForceGroups` (from `src/gromacs/mdtypes/multipletimestepping.h`).
pub static MTS_FORCE_GROUPS: &[&str] = &[
    "longrange-nonbonded",
    "nonbonded",
    "pair",
    "dihedral",
    "angle",
    "pull",
    "awh",
];

/// `NbkernelElecType` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static NBKERNEL_ELEC_TYPE: &[&str] = &[
    "None",
    "Coulomb",
    "Reaction-Field",
    "Cubic-Spline-Table",
    "Ewald",
];

/// `NbkernelVdwType` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static NBKERNEL_VDW_TYPE: &[&str] = &[
    "None",
    "Lennard-Jones",
    "Buckingham",
    "Cubic-Spline-Table",
    "LJEwald",
];

/// `NbnxmBenchMarkCombRule` (from `src/gromacs/nbnxm/benchmark/bench_setup.cpp`).
pub static NBNXM_BENCH_MARK_COMB_RULE: &[&str] = &[
    "geom.",
    "LB",
    "none",
];

/// `NbnxmBenchMarkInteractionModifiers` (from `src/gromacs/nbnxm/benchmark/bench_setup.cpp`).
pub static NBNXM_BENCH_MARK_INTERACTION_MODIFIERS: &[&str] = &[
    "PotShift",
    "PotSwitch",
    "ForceSwitch",
];

/// `NbnxmBenchMarkKernels` (from `src/gromacs/nbnxm/benchmark/bench_setup.cpp`).
pub static NBNXM_BENCH_MARK_KERNELS: &[&str] = &[
    "auto",
    "no",
    "4xM",
    "2xMM",
];

/// `NhcUsage` (from `src/gromacs/modularsimulator/nosehooverchains.cpp`).
pub static NHC_USAGE: &[&str] = &[
    "System",
    "Barostat",
];

/// `NNPotEmbedding` (from `src/gromacs/applied_forces/nnpot/nnpotoptions.cpp`).
pub static NNPOT_EMBEDDING: &[&str] = &[
    "mechanical",
    "electrostatic-model",
];

/// `NonBondedEnergyTerms` (from `src/gromacs/mdlib/energyoutput.cpp`).
pub static NON_BONDED_ENERGY_TERMS: &[&str] = &[
    "Coul-SR",
    "LJ-SR",
    "Buck-SR",
    "Coul-14",
    "LJ-14",
];

/// `Normalization` (from `src/gromacs/trajectoryanalysis/modules/rdf.cpp`).
pub static NORMALIZATION: &[&str] = &[
    "rdf",
    "number_density",
    "none",
];

/// `ParticleType` (from `src/gromacs/topology/atoms.cpp`).
pub static PARTICLE_TYPE: &[&str] = &[
    "Atom",
    "Nucleus",
    "Shell",
    "Bond",
    "VSite",
];

/// `PbcType` (from `src/gromacs/pbcutil/pbc.cpp`).
pub static PBC_TYPE: &[&str] = &[
    "xyz",
    "no",
    "xy",
    "screw",
    "unset",
];

/// `PdbAtomsSelection` (from `src/gromacs/trajectoryanalysis/modules/select.cpp`).
pub static PDB_ATOMS_SELECTION: &[&str] = &[
    "all",
    "maxsel",
    "selected",
];

/// `PdbRecordType` (from `src/gromacs/fileio/pdbio.cpp`).
pub static PDB_RECORD_TYPE: &[&str] = &[
    "ATOM  ",
    "HETATM",
    "ANISOU",
    "CRYST1",
    "COMPND",
    "MODEL",
    "ENDMDL",
    "TER",
    "HEADER",
    "TITLE",
    "REMARK",
    "CONECT",
];

/// `PmeLoadBalancingLimit` (from `src/gromacs/ewald/pme_load_balancing.cpp`).
pub static PME_LOAD_BALANCING_LIMIT: &[&str] = &[
    "no",
    "box size",
    "domain decomposition",
    "PME grid restriction",
    "maximum allowed grid scaling",
];

/// `PmeStage` (from `src/gromacs/timing/wallcycle.cpp`).
pub static PME_STAGE: &[&str] = &[
    "PME spline",
    "PME spread",
    "PME spline + spread",
    "PME 3D-FFT r2c",
    "PME solve",
    "PME 3D-FFT c2r",
    "PME gather",
];

/// `PPStretches` (from `src/gromacs/trajectoryanalysis/modules/dssp.cpp`).
pub static PPSTRETCHES: &[&str] = &[
    "shortened",
    "default",
];

/// `PressureCoupling` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static PRESSURE_COUPLING: &[&str] = &[
    "No",
    "Berendsen",
    "Parrinello-Rahman",
    "Isotropic",
    "MTTK",
    "C-rescale",
];

/// `PressureCouplingType` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static PRESSURE_COUPLING_TYPE: &[&str] = &[
    "Isotropic",
    "Semiisotropic",
    "Anisotropic",
    "Surface-Tension",
];

/// `PullGroupGeometry` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static PULL_GROUP_GEOMETRY: &[&str] = &[
    "distance",
    "direction",
    "cylinder",
    "direction-periodic",
    "direction-relative",
    "angle",
    "dihedral",
    "angle-axis",
    "transformation",
];

/// `PullingAlgorithm` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static PULLING_ALGORITHM: &[&str] = &[
    "umbrella",
    "constraint",
    "constant-force",
    "flat-bottom",
    "flat-bottom-high",
    "external-potential",
];

/// `QMMMQMMethod` (from `src/gromacs/applied_forces/qmmm/qmmmtypes.h`).
pub static QMMMQMMETHOD: &[&str] = &[
    "PBE",
    "PBE-D3",
    "BLYP",
    "BLYP-D3",
    "PBE0",
    "PBE0-D3",
    "B3LYP",
    "B3LYP-D3",
    "CAM-B3LYP",
    "CAM-B3LYP-D3",
    "WB97X",
    "WB97X-D3",
    "INPUT",
];

/// `RefCoordScaling` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static REF_COORD_SCALING: &[&str] = &[
    "No",
    "All",
    "COM",
];

/// `ReplaceType` (from `src/gromacs/gmxpreprocess/ter_db.cpp`).
pub static REPLACE_TYPE: &[&str] = &[
    "replace",
    "add",
    "delete",
];

/// `ReplicaExchangeType` (from `src/gromacs/mdrun/replicaexchange.cpp`).
pub static REPLICA_EXCHANGE_TYPE: &[&str] = &[
    "temperature",
    "lambda",
    "end_single_marker",
    "temperature and lambda",
];

/// `ResidueNumbering` (from `src/gromacs/trajectoryanalysis/modules/select.cpp`).
pub static RESIDUE_NUMBERING: &[&str] = &[
    "number",
    "index",
];

/// `RotationGroupFitting` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static ROTATION_GROUP_FITTING: &[&str] = &[
    "rmsd",
    "norm",
    "potential",
];

/// `RotationType` (from `src/gromacs/gmxpreprocess/insert_molecules.cpp`).
pub static ROTATION_TYPE: &[&str] = &[
    "xyz",
    "z",
    "none",
];

/// `RtpResType` (from `src/gromacs/gmxpreprocess/pdb2gmx.cpp`).
pub static RTP_RES_TYPE: &[&str] = &[
    "auto",
    "no",
    "yes",
];

/// `ScatterType` (from `src/gromacs/trajectoryanalysis/modules/scattering.cpp`).
pub static SCATTER_TYPE: &[&str] = &[
    "saxs",
    "sans",
];

/// `SecondaryStructureTypes` (from `src/gromacs/trajectoryanalysis/modules/dssp.cpp`).
pub static SECONDARY_STRUCTURE_TYPES: &[&str] = &[
    "Loops",
    "Breaks",
    "Bends",
    "Turns",
    "PP\\\\sII\\\\N-Helices",
    "\\\\xp\\\\f{}-Helices",
    "3\\\\s10\\\\N-Helices",
    "\\\\xb\\\\f{}-Strands",
    "\\\\xb\\\\f{}-Bridges",
    "\\\\xa\\\\f{}-Helices",
];

/// `SeparateDhdlFile` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static SEPARATE_DHDL_FILE: &[&str] = &[
    "yes",
    "no",
];

/// `SimulatedAnnealing` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static SIMULATED_ANNEALING: &[&str] = &[
    "No",
    "Single",
    "Periodic",
];

/// `SimulatedTempering` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static SIMULATED_TEMPERING: &[&str] = &[
    "geometric",
    "exponential",
    "linear",
];

/// `SimulationAtomGroupType` (from `src/gromacs/topology/topology.cpp`).
pub static SIMULATION_ATOM_GROUP_TYPE: &[&str] = &[
    "T-Coupling",
    "Energy Mon.",
    "Acc. not used",
    "Freeze",
    "User1",
    "User2",
    "VCM",
    "Compressed X",
    "Or. Res. Fit",
    "QMMM",
];

/// `SingleDimDiffType` (from `src/gromacs/trajectoryanalysis/modules/msd.cpp`).
pub static SINGLE_DIM_DIFF_TYPE: &[&str] = &[
    "x",
    "y",
    "z",
    "unused",
];

/// `SoftcoreType` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static SOFTCORE_TYPE: &[&str] = &[
    "beutler",
    "gapsys",
];

/// `SolventModel` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static SOLVENT_MODEL: &[&str] = &[
    "No",
    "SPC",
    "TIP4p",
];

/// `StartingBehavior` (from `src/gromacs/mdrunutility/handlerestart.cpp`).
pub static STARTING_BEHAVIOR: &[&str] = &[
    "restart with appending",
    "restart without appending",
    "new simulation",
];

/// `StateAwhEntry` (from `src/gromacs/fileio/checkpoint.cpp`).
pub static STATE_AWH_ENTRY: &[&str] = &[
    "awh_in_initial",
    "awh_equilibrateHistogram",
    "awh_histsize",
    "awh_npoints",
    "awh_coordpoint",
    "awh_umbrellaGridpoint",
    "awh_updatelist",
    "awh_logScaledSampleWeight",
    "awh_numupdates",
    "awh_forceCorrelationGrid",
];

/// `StateEnergyEntry` (from `src/gromacs/fileio/checkpoint.cpp`).
pub static STATE_ENERGY_ENTRY: &[&str] = &[
    "energy_n",
    "energy_aver",
    "energy_sum",
    "energy_nsum",
    "energy_sum_sim",
    "energy_nsum_sim",
    "energy_nsteps",
    "energy_nsteps_sim",
    "energy_delta_h_nn",
    "energy_delta_h_list",
    "energy_delta_h_start_time",
    "energy_delta_h_start_lambda",
];

/// `StateEntry` (from `src/gromacs/fileio/checkpoint.cpp`).
pub static STATE_ENTRY: &[&str] = &[
    "FE-lambda",
    "box",
    "box-rel",
    "box-v",
    "pres_prev",
    "nosehoover-xi",
    "thermostat-integral",
    "x",
    "v",
    "sdx-unsupported",
    "CGp",
    "LD-rng-unsupported",
    "LD-rng-i-unsupported",
    "disre_initf",
    "disre_rm3tav",
    "orire_initf",
    "orire_Dtav",
    "svir_prev",
    "nosehoover-vxi",
    "v_eta",
    "vol0",
    "nhpres_xi",
    "nhpres_vxi",
    "fvir_prev",
    "fep_state",
    "MC-rng-unsupported",
    "MC-rng-i-unsupported",
    "barostat-integral",
];

/// `StateFepEntry` (from `src/gromacs/fileio/checkpoint.cpp`).
pub static STATE_FEP_ENTRY: &[&str] = &[
    "bEquilibrated",
    "Number at State Stats",
    "Number at State Equil",
    "Wang-Landau Histogram",
    "Wang-Landau Delta",
    "Weights",
    "Free Energies",
    "minvar",
    "variance",
    "accumulated_plus",
    "accumulated_minus",
    "accumulated_plus_2",
    "accumulated_minus_2",
    "Tij",
    "Tij_empirical",
];

/// `StateKineticEntry` (from `src/gromacs/fileio/checkpoint.cpp`).
pub static STATE_KINETIC_ENTRY: &[&str] = &[
    "Ekin_n",
    "Ekinh",
    "dEkindlambda",
    "mv_cos",
    "Ekinf",
    "Ekinh_old",
    "EkinScaleF_NHC",
    "EkinScaleH_NHC",
    "Vscale_NHC",
    "Ekin_Total",
];

/// `StatePullCoordEntry` (from `src/gromacs/fileio/checkpoint.cpp`).
pub static STATE_PULL_COORD_ENTRY: &[&str] = &[
    "reference-sum",
    "sum",
    "dr01-sum",
    "dr23-sum",
    "dr45-sum",
    "fscal-sum",
    "dynax-sum",
];

/// `StatePullEntry` (from `src/gromacs/fileio/checkpoint.cpp`).
pub static STATE_PULL_ENTRY: &[&str] = &[
    "pullhistory_numcoordinates",
    "pullhistory_numgroups",
    "pullhistory_numvaluesinxsum",
    "pullhistory_numvaluesinfsum",
];

/// `StatePullGroupEntry` (from `src/gromacs/fileio/checkpoint.cpp`).
pub static STATE_PULL_GROUP_ENTRY: &[&str] = &[
    "coordinate-sum",
];

/// `StopCondition` (from `src/gromacs/mdlib/sighandler.cpp`).
pub static STOP_CONDITION: &[&str] = &[
    "None",
    "Stop at the next neighbor search step",
    "Stop at the next step",
    "Abort",
];

/// `SurfaceType` (from `src/gromacs/trajectoryanalysis/modules/rdf.cpp`).
pub static SURFACE_TYPE: &[&str] = &[
    "no",
    "mol",
    "res",
];

/// `SwapGroupSplittingType` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static SWAP_GROUP_SPLITTING_TYPE: &[&str] = &[
    "Split0",
    "Split1",
    "Solvent",
];

/// `SwapType` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static SWAP_TYPE: &[&str] = &[
    "no",
    "X",
    "Y",
    "Z",
];

/// `TemperatureCoupling` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static TEMPERATURE_COUPLING: &[&str] = &[
    "No",
    "Berendsen",
    "Nose-Hoover",
    "yes",
    "Andersen",
    "Andersen-massive",
    "V-rescale",
];

/// `TimeUnit` (from `src/gromacs/fileio/oenv.cpp`).
pub static TIME_UNIT: &[&str] = &[
    "fs",
    "ps",
    "ns",
    "us",
    "ms",
    "s",
];

/// `TwoDimDiffType` (from `src/gromacs/trajectoryanalysis/modules/msd.cpp`).
pub static TWO_DIM_DIFF_TYPE: &[&str] = &[
    "x",
    "y",
    "z",
    "unused",
];

/// `UnitCellType` (from `src/gromacs/pbcutil/pbcenums.cpp`).
pub static UNIT_CELL_TYPE: &[&str] = &[
    "Triclinic",
    "Rectangular",
    "Compact",
];

/// `VanDerWaalsPotential` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static VAN_DER_WAALS_POTENTIAL: &[&str] = &[
    "None",
    "LJ",
    "Buckingham",
];

/// `VanDerWaalsType` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static VAN_DER_WAALS_TYPE: &[&str] = &[
    "Cut-off",
    "Switch",
    "Shift",
    "User",
    "Encad-shift (unused)",
    "PME",
];

/// `VSitesType` (from `src/gromacs/gmxpreprocess/pdb2gmx.cpp`).
pub static VSITES_TYPE: &[&str] = &[
    "none",
    "hydrogens",
    "aromatics",
];

/// `WallCycleCounter` (from `src/gromacs/timing/include/gromacs/timing/wallcycle.h`).
pub static WALL_CYCLE_COUNTER: &[&str] = &[
    "Run",
    "Step",
    "PP during PME",
    "Domain decomp.",
    "DD comm. load",
    "DD comm. bounds",
    "Vsite constr.",
    "Send X to PME",
    "Neighbor search",
    "Launch PP GPU ops.",
    "Comm. coord.",
    "Force",
    "",
    "",
    "",
    "",
    "",
    "Wait + Comm. F",
    "PME mesh",
    "PME GPU mesh",
    "PME redist. X/F",
    "PME spread",
    "PME gather",
    "PME 3D-FFT",
    "PME 3D-FFT Comm.",
    "PME solve LJ",
    "PME solve Elec",
    "Wait PME GPU D2H",
    "PME 3D-FFT",
    "PME solve",
    "Wait PME GPU gather",
    "Reduce GPU PME F",
    "Launch PME GPU ops.",
    "Wait PME Recv. PP X",
    "Wait PME GPU spread",
    "Wait GPU FFT to PME",
    "PME Halo exch comm",
    "PME wait for PP",
    "Wait + Recv. PME F",
    "Wait Bonded GPU",
    "Wait GPU NB nonloc.",
    "Wait GPU NB local",
    "Wait GPU state copy",
    "NB X/F buffer ops.",
    "Vsite spread",
    "COM pull force",
    "AWH",
    "Write traj.",
    "Update",
    "Constraints",
    "GPU constr. setup",
    "Kinetic energy",
    "Comm. energies",
    "Inter-sim. signal.",
    "Enforced rotation",
    "Add rot. forces",
    "Position swapping",
    "IMD",
    "MD Graph",
    "Test",
];

/// `WallCycleSubCounter` (from `src/gromacs/timing/include/gromacs/timing/wallcycle.h`).
pub static WALL_CYCLE_SUB_COUNTER: &[&str] = &[
    "DD update groups",
    "DD redist.",
    "DD NS grid + sort",
    "DD setup comm.",
    "DD make top.",
    "DD make constr.",
    "DD top. other",
    "DD GPU ops.",
    "NS grid local",
    "NS grid non-local",
    "NS search local",
    "NS search non-local",
    "GPU Bonded list update",
    "Bonded F",
    "Bonded-FEP F",
    "Restraints F",
    "Listed buffer ops.",
    "NB pruning",
    "NB F kernel",
    "NB F clear",
    "NB FEP",
    "NB FEP reduction",
    "Launch GPU NB tasks",
    "Launch GPU Bonded",
    "Launch state copy",
    "Ewald F correction",
    "NB X buffer ops.",
    "NB F buffer ops.",
    "Clear force buffer",
    "Launch GPU NB X ops.",
    "Launch GPU NB F ops.",
    "Launch GPU Comm. X",
    "Launch GPU Comm. F",
    "Launch GPU update",
    "Launch PME GPU FFT",
    "Graph wait pre-capture",
    "Graph capture",
    "Graph instantiate/upd.",
    "Graph wait pre-launch",
    "Graph launch",
    "Constraints Comm.",
    "LINCS setup",
    "Settle setup",
    "GPU LINCS setup",
    "GPU settle setup",
    "Test subcounter",
];

/// `WallType` (from `src/gromacs/mdtypes/md_enums.cpp`).
pub static WALL_TYPE: &[&str] = &[
    "9-3",
    "10-4",
    "table",
    "12-6",
];

/// `WarningType` (from `src/gromacs/fileio/warninp.cpp`).
pub static WARNING_TYPE: &[&str] = &[
    "NOTE",
    "WARNING",
    "ERROR",
];

/// `WaterType` (from `src/gromacs/gmxpreprocess/pdb2gmx.cpp`).
pub static WATER_TYPE: &[&str] = &[
    "select",
    "none",
    "opc",
    "opc3",
    "spc",
    "spce",
    "tip3p",
    "tip4p",
    "tip4pew",
    "tip5p",
    "tips3p",
];

/// `XdrDataType` (from `src/gromacs/fileio/libxdrf.cpp`).
pub static XDR_DATA_TYPE: &[&str] = &[
    "int",
    "float",
    "double",
    "large int",
    "char",
    "string",
];

/// `XvgFormat` (from `src/gromacs/analysisdata/modules/plot.cpp`).
pub static XVG_FORMAT: &[&str] = &[
    "xmgrace",
    "xmgr",
    "none",
];

/// `YesNoType` (from `src/gromacs/fileio/readinp.cpp`).
pub static YES_NO_TYPE: &[&str] = &[
    "yes",
    "no",
];

