//! Self-contained tests: they only use data generated by this crate, so they
//! run without GROMACS or any external test files.

use gmx_rs_tools::frame::{Atom, Atoms, Frame, PbcType, ResInfo};
use gmx_rs_tools::index::{self, IndexGroup};
use gmx_rs_tools::{gro, tpr, trr, xdr, xtc};
use gmx_rs_tools::trx::{read_coordinates, CoordinateReader, FrameRange};

fn sample_frame(n: usize, seed: f32) -> Frame {
    let mut f = Frame::new(n);
    f.step = Some(7);
    f.time = Some(1.25);
    f.lambda = Some(0.0);
    f.boxm = Some([
        [2.5, 0.0, 0.0],
        [0.0, 2.5, 0.0],
        [0.25, 0.25, 2.0],
    ]);
    f.pbc_type = PbcType::Xyz;
    f.x = Some(
        (0..n)
            .map(|i| {
                [
                    seed + i as f32 * 0.01,
                    seed + i as f32 * 0.02,
                    seed + i as f32 * 0.03,
                ]
            })
            .collect(),
    );
    f.v = Some(
        (0..n)
            .map(|i| [i as f32 * 0.001, 0.0, -0.001 * i as f32])
            .collect(),
    );
    f
}

#[test]
fn xdr_strings_and_integers_roundtrip() {
    let mut w = xdr::Writer::new();
    w.int(-17);
    w.int64(1 << 40);
    w.double(1.0 / 3.0);
    w.gmx_string("VERSION 2026.3");
    w.gmx_string("");
    let bytes = w.into_vec();

    let mut r = xdr::Reader::new(&bytes);
    assert_eq!(r.int().unwrap(), -17);
    assert_eq!(r.int64().unwrap(), 1 << 40);
    assert!((r.double().unwrap() - 1.0 / 3.0).abs() < 1e-15);
    assert_eq!(r.gmx_string().unwrap(), "VERSION 2026.3");
    assert_eq!(r.gmx_string().unwrap(), "");
}

/// Compressed XTC coordinates are lossy by design (the writer rounds to
/// `prec`), so the test checks the reconstruction error instead of equality.
#[test]
fn xtc_roundtrip_is_within_precision() {
    let prec = 1000.0f32;
    let original = sample_frame(500, 1.0);
    let mut w = xdr::Writer::new();
    xtc::write_frame(&mut w, &original, prec);
    let bytes = w.into_vec();

    let mut r = xdr::Reader::new(&bytes);
    let read = xtc::read_frame(&mut r).unwrap().expect("frame");
    assert_eq!(read.natoms, original.natoms);
    assert_eq!(read.step, original.step);
    assert!((read.time.unwrap() - 1.25).abs() < 1e-6);
    assert_eq!(read.boxm.unwrap(), original.boxm.unwrap());
    for (a, b) in read.x.as_ref().unwrap().iter().zip(original.x.as_ref().unwrap()) {
        for d in 0..3 {
            assert!(
                (a[d] - b[d]).abs() <= 1.0 / prec,
                "coordinate {a:?} differs from {b:?} by more than the precision"
            );
        }
    }
}

#[test]
fn xtc_multi_frame_stream_stops_cleanly() {
    let mut w = xdr::Writer::new();
    xtc::write_frame(&mut w, &sample_frame(120, 1.0), 1000.0);
    xtc::write_frame(&mut w, &sample_frame(120, 2.0), 1000.0);
    let bytes = w.into_vec();

    let mut r = xdr::Reader::new(&bytes);
    let mut n = 0;
    while xtc::read_frame(&mut r).unwrap().is_some() {
        n += 1;
    }
    assert_eq!(n, 2);
}

#[test]
fn trr_roundtrip_is_exact() {
    let original = sample_frame(64, 0.5);
    let mut w = xdr::Writer::new();
    trr::write_frame(&mut w, &original);
    let bytes = w.into_vec();

    let mut r = xdr::Reader::new(&bytes);
    let read = trr::read_frame(&mut r).unwrap().expect("frame");
    assert_eq!(read.x, original.x);
    assert_eq!(read.v, original.v);
    assert_eq!(read.boxm, original.boxm);
}

fn sample_atoms() -> Atoms {
    let mut atoms = Atoms::default();
    atoms.name = "test".to_string();
    atoms.resinfo.push(ResInfo {
        name: "ALA".to_string(),
        nr: 1,
        ic: b' ',
        chainid: b'A',
    });
    atoms.resinfo.push(ResInfo {
        name: "SOL".to_string(),
        nr: 2,
        ic: b' ',
        chainid: b' ',
    });
    let names = ["N", "CA", "C"];
    for (i, n) in names.iter().enumerate() {
        atoms.atom.push(Atom {
            name: n.to_string(),
            atom_type: n.to_string(),
            atom_type_b: n.to_string(),
            resind: 0,
            mass: 12.0,
            charge: 0.0,
            mass_b: 12.0,
            charge_b: 0.0,
            ptype: 0,
            atomnumber: 6,
            elem: "C".to_string(),
            type_id: i as u16,
            type_id_b: i as u16,
        });
    }
    for i in 0..3 {
        atoms.atom.push(Atom {
            name: ["OW", "HW1", "HW2"][i].to_string(),
            atom_type: "O".to_string(),
            atom_type_b: "O".to_string(),
            resind: 1,
            mass: 16.0,
            charge: 0.0,
            mass_b: 16.0,
            charge_b: 0.0,
            ptype: 0,
            atomnumber: 8,
            elem: "O".to_string(),
            type_id: i as u16,
            type_id_b: i as u16,
        });
    }
    atoms
}

#[test]
fn gro_write_then_read_preserves_topology_and_coordinates() {
    let atoms = sample_atoms();
    let frame = sample_frame(atoms.nr(), 0.0);
    let index: Vec<usize> = (0..atoms.nr()).collect();
    let prefixes = gro::atom_prefixes(&atoms, &index);
    let mut out: Vec<u8> = Vec::new();
    gro::write_frame(
        &mut out,
        "test system",
        &prefixes,
        frame.x.as_ref().unwrap(),
        &index,
        None,
        &frame.boxm.unwrap(),
    );
    let out = String::from_utf8(out).unwrap();

    let path = std::env::temp_dir().join("gmx-rs-tools-gro_roundtrip.gro");
    std::fs::write(&path, &out).unwrap();
    let frames = gro::read_all(path.to_str().unwrap()).unwrap();
    assert_eq!(frames.len(), 1);
    assert_eq!(frames[0].natoms, atoms.nr());
    let read_atoms = frames[0].atoms.as_ref().unwrap();
    assert_eq!(read_atoms.resinfo[0].name, "ALA");
    assert_eq!(read_atoms.resinfo[1].name, "SOL");
    assert_eq!(read_atoms.atom[3].name, "OW");
    for (a, b) in frames[0].x.as_ref().unwrap().iter().zip(frame.x.as_ref().unwrap()) {
        for d in 0..3 {
            assert!((a[d] - b[d]).abs() < 1e-3);
        }
    }
    let _ = std::fs::remove_file(&path);
}

#[test]
fn index_file_roundtrip_and_group_lookup() {
    let groups = vec![
        IndexGroup::new("System", (0..40).collect()),
        IndexGroup::new("Protein", (0..17).collect()),
        IndexGroup::new("Water", (17..40).collect()),
        IndexGroup::new("Water2", (17..40).collect()),
    ];
    let path = std::env::temp_dir().join("gmx-rs-tools-roundtrip.ndx");
    index::write_ndx(path.to_str().unwrap(), &groups, false, 40).unwrap();
    let read = index::read_ndx(path.to_str().unwrap()).unwrap();
    assert_eq!(read.len(), 4);
    assert_eq!(read[1].name, "Protein");
    assert_eq!(read[1].particle_indices, groups[1].particle_indices);

    // Whole name, prefix and substring matching (findGroupTemplated).
    assert_eq!(index::find_group("protein", &read), 1);
    assert_eq!(index::find_group("Prot", &read), 1);
    // An exact name wins over the longer prefix match.
    assert_eq!(index::find_group("Water", &read), 2);
    // A prefix that matches two groups is rejected as ambiguous.
    assert_eq!(index::find_group("Wat", &read), -1);
    // "o" only occurs in "Protein", so the substring match is unique.
    assert_eq!(index::find_group("o", &read), 1);
    let _ = std::fs::remove_file(&path);
}

#[test]
fn analyse_generates_default_groups() {
    let atoms = sample_atoms();
    let groups = index::analyse(&atoms, false);
    let names: Vec<&str> = groups.iter().map(|g| g.name.as_str()).collect();
    assert!(names.contains(&"System"));
    assert!(names.contains(&"Protein"));
    assert!(names.contains(&"Water"));
    assert!(names.contains(&"SOL"));
    assert!(names.contains(&"non-Water"));
    let water = groups.iter().find(|g| g.name == "Water").unwrap();
    assert_eq!(water.particle_indices, vec![3, 4, 5]);
}

/// The tpr header is plain XDR and survives a write/read cycle.
#[test]
fn tpr_header_roundtrip() {
    let mut w = xdr::Writer::new();
    w.gmx_string("VERSION 2026.3");
    w.int(4);
    w.int(138);
    w.int(29);
    w.gmx_string("release");
    w.int(923);
    w.int(1);
    w.int(0);
    w.float(0.0);
    w.bool(true);
    w.bool(true);
    w.bool(true);
    w.bool(true);
    w.bool(false);
    w.bool(true);
    w.int64(4);
    w.opaque(&[1, 2, 3, 4]);

    let bytes = w.into_vec();
    let file = tpr::TprFile::from_bytes(&bytes).unwrap();
    assert_eq!(file.header.file_version, 138);
    assert_eq!(file.header.file_generation, 29);
    assert_eq!(file.header.natoms, 923);
    assert!(file.header.b_ir && file.header.b_box && !file.header.b_f);
    assert_eq!(file.body, vec![1, 2, 3, 4]);
    assert_eq!(file.to_bytes(), bytes);
}

/// Reads coordinates out of a trajectory: time window, frame stride and atom
/// selection all behave like `gmx trjconv` (`-b`/`-e`/`-skip` and a group).
#[test]
fn coordinate_reader_applies_range_and_selection() {
    let path = std::env::temp_dir().join("gmx-rs-tools-coords_test.xtc");
    let mut w = xdr::Writer::new();
    for f in 0..6 {
        let mut frame = sample_frame(10, f as f32);
        frame.time = Some(f as f64 * 0.1);
        frame.step = Some(f as i64 * 100);
        xtc::write_frame(&mut w, &frame, 1000.0);
    }
    std::fs::write(&path, w.into_vec()).unwrap();
    let path = path.to_str().unwrap();

    // Every frame, every atom.
    let all = read_coordinates(path, None, FrameRange::default()).unwrap();
    assert_eq!(all.len(), 6);
    assert_eq!(all[0].x.len(), 10);
    assert_eq!(all[0].step, Some(0));
    // Times are stored as single precision in an XTC file.
    assert!((all[3].time.unwrap() - 0.3).abs() < 1e-6);

    // Time window plus stride: this is what `-b 0.2 -e 0.5 -skip 2` does.
    let range = FrameRange {
        begin: Some(0.2),
        end: Some(0.5),
        skip: 2,
        max_frames: None,
    };
    let window = read_coordinates(path, None, range).unwrap();
    let times: Vec<f64> = window.iter().map(|f| f.time.unwrap()).collect();
    assert_eq!(times.len(), 2);
    assert!((times[0] - 0.2).abs() < 1e-6 && (times[1] - 0.4).abs() < 1e-6);

    // Selection: the coordinates must be the ones of the selected atoms.
    let selection = vec![7usize, 2, 9];
    let mut reader = CoordinateReader::open(path, Some(&selection), FrameRange::default())
        .unwrap()
        .1;
    let first = reader.next_frame().unwrap().unwrap();
    assert_eq!(first.x.len(), 3);
    let full = read_coordinates(path, None, FrameRange::default()).unwrap();
    for (i, &a) in selection.iter().enumerate() {
        for d in 0..3 {
            assert!((first.x[i][d] - full[0].x[a][d]).abs() < 1e-9);
        }
    }

    // max_frames limits the amount of data returned.
    let limited = FrameRange {
        max_frames: Some(2),
        ..Default::default()
    };
    assert_eq!(read_coordinates(path, None, limited).unwrap().len(), 2);

    let _ = std::fs::remove_file(path);
}

/// Run input files written by several GROMACS releases are parsed with the
/// version-dependent layouts of `tpxio.cpp` (the body switched from XDR to the
/// compact in-memory serializer in tpx version 119).
///
/// The files ship with the GROMACS source tree, so the test is skipped when the
/// crate is built outside of it.
#[test]
fn old_tpr_versions_parse() {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join("src/gromacs");
    // (relative path, expected natoms, expected nsteps, expected tpx version)
    let cases: [(&str, i32, i64, i32); 5] = [
        ("trajectoryanalysis/tests/freevolume.tpr", 5540, 50000000, 73),
        ("trajectoryanalysis/tests/clustsize.tpr", 24, 25000, 110),
        ("energyanalysis/tests/dhdl.tpr", 1793, 500, 110),
        ("energyanalysis/tests/orires.tpr", 1007, 10, 111),
        ("trajectoryanalysis/tests/trpcage.tpr", 3793, 5000, 129),
    ];
    let mut checked = 0;
    for (rel, natoms, nsteps, version) in cases {
        let path = root.join(rel);
        let Ok(bytes) = std::fs::read(&path) else {
            continue;
        };
        let path = path.to_string_lossy().to_string();
        let file = tpr::TprFile::from_bytes(&bytes).expect("header");
        assert_eq!(
            file.header.file_version, version,
            "{path} has an unexpected tpx version"
        );
        let body = tpr::parse_body(&file.header, &file.body).expect("body");
        assert_eq!(file.header.natoms, natoms, "{path}");
        let ir = body.ir.as_ref().expect("inputrec");
        assert_eq!(ir.nsteps, nsteps, "{path}");
        assert!((ir.delta_t - 0.002).abs() < 1e-9, "{path}");
        // The topology must be complete enough to build the default groups.
        let mtop = body.mtop.as_ref().expect("topology");
        let atoms = mtop.global_atoms();
        assert_eq!(atoms.nr(), natoms as usize, "{path}");
        // The Lennard-Jones pairs have to be readable straight out of the
        // force field parameters (`nbfp[i * atnr + j]`).
        let atnr = mtop.ffparams.atnr_usize();
        assert!(atnr > 0, "{path}");
        let pairs: Vec<(f64, f64)> = (0..atnr * atnr)
            .filter_map(|i| mtop.ffparams.lj_sr(i))
            .collect();
        assert_eq!(pairs.len(), atnr * atnr, "{path}");
        assert!(pairs.iter().all(|(c6, c12)| *c6 >= 0.0 && *c12 >= 0.0), "{path}");
        let groups = index::analyse(&atoms, false);
        assert!(!groups.is_empty(), "{path}");
        checked += 1;
    }
    if checked == 0 {
        eprintln!("skipping: the GROMACS test run input files were not found");
    } else {
        assert_eq!(checked, 5);
    }
}
